### ISSUE TITLE
Installing the package doesn't create a settings.yml

### ISSUE THREAD

**Issue by Eroldin** [nikitabobko/gcal-notifier-kotlin-gtk#13] opened 2021-04-08 15:39 UTC
Exception in thread "main" java.io.FileNotFoundException: /home/eroldin/.config/gcal-notifier-kotlin-gtk/settings.yml (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.PrintWriter.<init>(PrintWriter.java:184)
	at ru.nikitabobko.gcalnotifier.support.FileReaderWriterImpl.writeToFile(FileReaderWriter.kt:17)
	at ru.nikitabobko.gcalnotifier.settings.SettingsImpl$memoizedSettings$2.invoke(Settings.kt:54)
	at ru.nikitabobko.gcalnotifier.settings.SettingsImpl$memoizedSettings$2.invoke(Settings.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ru.nikitabobko.gcalnotifier.settings.SettingsImpl.getMemoizedSettings(Settings.kt)
	at ru.nikitabobko.gcalnotifier.settings.SettingsImpl.access$getMemoizedSettings$p(Settings.kt:25)
	at ru.nikitabobko.gcalnotifier.settings.SettingsImpl$SettingItem.getValue(Settings.kt:96)
	at ru.nikitabobko.gcalnotifier.settings.SettingsImpl.getMaxNumberOfEventsToShowInPopupMenu(Settings.kt)
	at ru.nikitabobko.gcalnotifier.view.ViewJavaGnome$update$1.invoke(View.kt:119)
	at ru.nikitabobko.gcalnotifier.view.ViewJavaGnome$update$1.invoke(View.kt:46)
	at ru.nikitabobko.gcalnotifier.view.ViewJavaGnome.runOnUiThread(View.kt:225)
	at ru.nikitabobko.gcalnotifier.view.ViewJavaGnome.update(View.kt:118)
	at ru.nikitabobko.gcalnotifier.controller.ControllerImpl.applicationStarted(Controller.kt:167)
	at ru.nikitabobko.gcalnotifier.MainKt.main(Main.kt:29)
	
OS: Manjaro

**Comment by nikitabobko** [comment] 2021-05-29 12:47
Duplicate of #12

**Closed as completed by nikitabobko** 2021-05-29 12:47 UTC

**Comment by nikitabobko** [comment] 2021-05-29 12:55
2.0.9 with the fix is released:
https://aur.archlinux.org/packages/gcal-notifier-kotlin-gtk
https://github.com/nikitabobko/gcal-notifier-kotlin-gtk/releases/tag/v2.0.9
